// Generated by CoffeeScript 1.9.3
(function() {
  describe("Age", function() {
    beforeEach(function() {
      return $("body").append("<time class='age' id='test' datetime='2010-01-01T12:00:00Z'>January 1, 2010 12:00</time>");
    });
    afterEach(function() {
      return $("#test").remove();
    });
    return it("should use an age", function() {
      $("#test").age();
      return expect($('#test').text()).not.toBe('January 1, 2010 12:00');
    });
  });

}).call(this);
