// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    $('.age.now').attr('datetime', new Date);
    $('.age.default').age();
    return $('.age.tiny').age({
      style: 'tiny'
    });
  });

}).call(this);
