// Generated by CoffeeScript 1.9.3
(function() {
  $(function() {
    $('.age.now').attr('datetime', new Date);
    $('.age.default').age();
    $('.age.tiny').age({
      style: 'tiny'
    });
    $('.age.expired').age({
      expired: 'expired'
    });
    return $('.age.pending').age({
      pending: 'pending'
    });
  });

}).call(this);
